-- 주문 30,000 건. 값은 id 로 계산해 어느 DB 에서 만들어도 같다 (RAND 를 쓰면 정답이 흔들린다).
--   customer_id : 1~2000, 고객당 15건
--   status      : PAID 85% / CANCELLED·REFUNDED·PENDING 각 5%
--   created_at  : 2026-01-01 부터 약 반년, 하루 160~170건
DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
    id INT PRIMARY KEY,
    order_no VARCHAR(20) NOT NULL,
    customer_id INT NOT NULL,
    status VARCHAR(10) NOT NULL,
    amount INT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- H2 도 돌도록: INSERT ... WITH 대신 파생 테이블, n * 104729 는 INT 를 넘어 둘로 쪼갬 (값은 같다).
INSERT INTO orders (id, order_no, customer_id, status, amount, created_at)
SELECT n,
       CONCAT('', 2026000000 + n),
       MOD(n * 7919, 2000) + 1,
       CASE MOD(n, 20) WHEN 0 THEN 'CANCELLED' WHEN 1 THEN 'REFUNDED' WHEN 2 THEN 'PENDING' ELSE 'PAID' END,
       MOD(n * 37, 991) * 100 + 1000,
       TIMESTAMPADD(MINUTE, MOD(MOD(n * 1000, 262800) * 100 + n * 4729, 262800), TIMESTAMP '2026-01-01 00:00:00')
FROM (
    SELECT a.v + b.v * 10 + c.v * 100 + e.v * 1000 + f.v * 10000 + 1 AS n
    FROM (SELECT 0 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
    CROSS JOIN (SELECT 0 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
    CROSS JOIN (SELECT 0 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
    CROSS JOIN (SELECT 0 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
    CROSS JOIN (SELECT 0 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) f
) seq
WHERE n <= 30000;

ANALYZE TABLE orders;

CREATE INDEX idx_orders_created ON orders (created_at);
