-- 주문 30,000 건. 값은 id 로 계산해 어느 DB 에서 만들어도 같다 (RAND 를 쓰면 정답이 흔들린다).
--   customer_id : 1~2000, 고객당 15건
--   status      : PAID 85% / CANCELLED·REFUNDED·PENDING 각 5%
--   created_at  : 2026-01-01 부터 약 반년, 하루 160~170건
DROP TABLE IF EXISTS orders;

CREATE TABLE orders (
    id INT PRIMARY KEY,
    order_no VARCHAR(20) NOT NULL,
    customer_id INT NOT NULL,
    status VARCHAR(10) NOT NULL,
    amount INT NOT NULL,
    created_at TIMESTAMP NOT NULL
);

-- H2 도 돌도록: INSERT ... WITH 대신 파생 테이블, n * 104729 는 INT 를 넘어 둘로 쪼갬 (값은 같다).
INSERT INTO orders (id, order_no, customer_id, status, amount, created_at)
SELECT n,
       CONCAT('', 2026000000 + n),
       MOD(n * 7919, 2000) + 1,
       CASE MOD(n, 20) WHEN 0 THEN 'CANCELLED' WHEN 1 THEN 'REFUNDED' WHEN 2 THEN 'PENDING' ELSE 'PAID' END,
       MOD(n * 37, 991) * 100 + 1000,
       TIMESTAMPADD(MINUTE, MOD(MOD(n * 1000, 262800) * 100 + n * 4729, 262800), TIMESTAMP '2026-01-01 00:00:00')
FROM (
    SELECT a.v + b.v * 10 + c.v * 100 + e.v * 1000 + f.v * 10000 + 1 AS n
    FROM (SELECT 0 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) a
    CROSS JOIN (SELECT 0 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) b
    CROSS JOIN (SELECT 0 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) c
    CROSS JOIN (SELECT 0 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) e
    CROSS JOIN (SELECT 0 AS v UNION ALL SELECT 1 UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5 UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9) f
) seq
WHERE n <= 30000;

ANALYZE TABLE orders;

-- VIP 회원 20 명. id 가 곧 orders.customer_id 다 (외래키는 걸지 않는다).
DROP TABLE IF EXISTS vip_members;

CREATE TABLE vip_members (
    id INT PRIMARY KEY,
    name VARCHAR(20) NOT NULL,
    tier VARCHAR(10) NOT NULL
);

INSERT INTO vip_members (id, name, tier) VALUES
(12, '김하늘', 'GOLD'),
(77, '이서준', 'PLATINUM'),
(150, '박지민', 'GOLD'),
(233, '최유나', 'GOLD'),
(318, '정민호', 'PLATINUM'),
(404, '강다은', 'GOLD'),
(512, '조현우', 'GOLD'),
(609, '윤채원', 'PLATINUM'),
(701, '장도현', 'GOLD'),
(777, '임소율', 'PLATINUM'),
(845, '한지호', 'GOLD'),
(930, '오예린', 'GOLD'),
(1024, '서태윤', 'PLATINUM'),
(1111, '신가은', 'GOLD'),
(1208, '권준서', 'GOLD'),
(1350, '황수아', 'GOLD'),
(1492, '안시우', 'PLATINUM'),
(1600, '송하린', 'GOLD'),
(1789, '류건우', 'GOLD'),
(1999, '전나연', 'GOLD');

ANALYZE TABLE vip_members;
